server:
  port: 8080
  # servlet:
    # context-path: /sample_backend
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sample
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:my-secret-pw}
    # url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sample
    # ?useSSL=false&serverTimezone=UTC
    # username: ${MYSQL_USER:root}
    # password: ${MYSQL_PASS:my-secret-pw}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        # format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect





# server:
#   port: 8080
#   servlet:
#     context-path: /sample_backend

# spring:
#     datasource:
#         driver-class-name: com.mysql.cj.jdbc.Driver
#         url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/sample
#         username: ${MYSQL_USER:root}
#         password: ${MYSQL_PASS:my-secret-pw}
#     transaction:
#         default-timeout: 5


# mybatis:
#     mapper-locations: classpath*:mybatis/*.xml
#     configuration:
#         map-underscore-to-camel-case: true
